#!/bin/sh
. /etc/openssl/read_uci
openssl ca -revoke /etc/openssl/$ENTITY/certs/$KEY_COMMON_NAME.crt -config /etc/openssl/openssl.cnf
openssl ca -gencrl -out /etc/openssl/$ENTITY/crl/crl.pem -config /etc/openssl/openssl.cnf