$(eval $(call PackageDir,batman-adv,batman-adv))
$(eval $(call PackageDir,babeld,babeld))
$(eval $(call PackageDir,bmx6,bmx6))
$(eval $(call PackageDir,olsrd,olsrd))
$(eval $(call PackageDir,batmand,batmand))
$(eval $(call PackageDir,luci-app-bmx6,luci-app-bmx6))
$(eval $(call PackageDir,bmxd,bmxd))
