/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "l2tp_rpc.h"
#define OPTSTRING(_var) _var.optstring_u.value
#define OPTSTRING_PTR(_var) ((_var.valid == 1) ? _var.optstring_u.value : NULL)

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
l2tp_app_info_get_1(struct l2tp_api_app_msg_data *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, L2TP_APP_INFO_GET, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_l2tp_api_app_msg_data, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
l2tp_system_modify_1(struct l2tp_api_system_msg_data params, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, L2TP_SYSTEM_MODIFY,
		(xdrproc_t) xdr_l2tp_api_system_msg_data, (caddr_t) &params,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
l2tp_system_get_1(struct l2tp_api_system_msg_data *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, L2TP_SYSTEM_GET, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_l2tp_api_system_msg_data, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
l2tp_peer_profile_create_1(struct l2tp_api_peer_profile_msg_data params, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, L2TP_PEER_PROFILE_CREATE,
		(xdrproc_t) xdr_l2tp_api_peer_profile_msg_data, (caddr_t) &params,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
l2tp_peer_profile_delete_1(char *name, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, L2TP_PEER_PROFILE_DELETE,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &name,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
l2tp_peer_profile_modify_1(struct l2tp_api_peer_profile_msg_data params, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, L2TP_PEER_PROFILE_MODIFY,
		(xdrproc_t) xdr_l2tp_api_peer_profile_msg_data, (caddr_t) &params,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
l2tp_peer_profile_get_1(char *name, struct l2tp_api_peer_profile_msg_data *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, L2TP_PEER_PROFILE_GET,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &name,
		(xdrproc_t) xdr_l2tp_api_peer_profile_msg_data, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
l2tp_peer_profile_list_1(struct l2tp_api_peer_profile_list_msg_data *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, L2TP_PEER_PROFILE_LIST, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_l2tp_api_peer_profile_list_msg_data, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
l2tp_tunnel_create_1(struct l2tp_api_tunnel_msg_data params, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, L2TP_TUNNEL_CREATE,
		(xdrproc_t) xdr_l2tp_api_tunnel_msg_data, (caddr_t) &params,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
l2tp_tunnel_delete_1(uint16_t tunnel_id, optstring tunnel_name, optstring reason, int *clnt_res,  CLIENT *clnt)
{
	l2tp_tunnel_delete_1_argument arg;
	arg.tunnel_id = tunnel_id;
	arg.tunnel_name = tunnel_name;
	arg.reason = reason;
	return (clnt_call (clnt, L2TP_TUNNEL_DELETE, (xdrproc_t) xdr_l2tp_tunnel_delete_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
l2tp_tunnel_modify_1(struct l2tp_api_tunnel_msg_data params, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, L2TP_TUNNEL_MODIFY,
		(xdrproc_t) xdr_l2tp_api_tunnel_msg_data, (caddr_t) &params,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
l2tp_tunnel_get_1(uint16_t tunnel_id, optstring tunnel_name, struct l2tp_api_tunnel_msg_data *clnt_res,  CLIENT *clnt)
{
	l2tp_tunnel_get_1_argument arg;
	arg.tunnel_id = tunnel_id;
	arg.tunnel_name = tunnel_name;
	return (clnt_call (clnt, L2TP_TUNNEL_GET, (xdrproc_t) xdr_l2tp_tunnel_get_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_l2tp_api_tunnel_msg_data, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
l2tp_tunnel_list_1(struct l2tp_api_tunnel_list_msg_data *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, L2TP_TUNNEL_LIST, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_l2tp_api_tunnel_list_msg_data, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
l2tp_tunnel_profile_create_1(struct l2tp_api_tunnel_profile_msg_data params, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, L2TP_TUNNEL_PROFILE_CREATE,
		(xdrproc_t) xdr_l2tp_api_tunnel_profile_msg_data, (caddr_t) &params,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
l2tp_tunnel_profile_delete_1(char *name, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, L2TP_TUNNEL_PROFILE_DELETE,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &name,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
l2tp_tunnel_profile_modify_1(struct l2tp_api_tunnel_profile_msg_data params, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, L2TP_TUNNEL_PROFILE_MODIFY,
		(xdrproc_t) xdr_l2tp_api_tunnel_profile_msg_data, (caddr_t) &params,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
l2tp_tunnel_profile_get_1(char *name, struct l2tp_api_tunnel_profile_msg_data *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, L2TP_TUNNEL_PROFILE_GET,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &name,
		(xdrproc_t) xdr_l2tp_api_tunnel_profile_msg_data, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
l2tp_tunnel_profile_list_1(struct l2tp_api_tunnel_profile_list_msg_data *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, L2TP_TUNNEL_PROFILE_LIST, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_l2tp_api_tunnel_profile_list_msg_data, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
l2tp_session_create_1(struct l2tp_api_session_msg_data params, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, L2TP_SESSION_CREATE,
		(xdrproc_t) xdr_l2tp_api_session_msg_data, (caddr_t) &params,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
l2tp_session_delete_1(uint16_t tunnel_id, optstring tunnel_name, uint16_t session_id, optstring session_name, optstring reason, int *clnt_res,  CLIENT *clnt)
{
	l2tp_session_delete_1_argument arg;
	arg.tunnel_id = tunnel_id;
	arg.tunnel_name = tunnel_name;
	arg.session_id = session_id;
	arg.session_name = session_name;
	arg.reason = reason;
	return (clnt_call (clnt, L2TP_SESSION_DELETE, (xdrproc_t) xdr_l2tp_session_delete_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
l2tp_session_modify_1(struct l2tp_api_session_msg_data params, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, L2TP_SESSION_MODIFY,
		(xdrproc_t) xdr_l2tp_api_session_msg_data, (caddr_t) &params,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
l2tp_session_get_1(uint16_t tunnel_id, optstring tunnel_name, uint16_t session_id, optstring session_name, struct l2tp_api_session_msg_data *clnt_res,  CLIENT *clnt)
{
	l2tp_session_get_1_argument arg;
	arg.tunnel_id = tunnel_id;
	arg.tunnel_name = tunnel_name;
	arg.session_id = session_id;
	arg.session_name = session_name;
	return (clnt_call (clnt, L2TP_SESSION_GET, (xdrproc_t) xdr_l2tp_session_get_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_l2tp_api_session_msg_data, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
l2tp_session_list_1(uint16_t tunnel_id, optstring tunnel_name, struct l2tp_api_session_list_msg_data *clnt_res,  CLIENT *clnt)
{
	l2tp_session_list_1_argument arg;
	arg.tunnel_id = tunnel_id;
	arg.tunnel_name = tunnel_name;
	return (clnt_call (clnt, L2TP_SESSION_LIST, (xdrproc_t) xdr_l2tp_session_list_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_l2tp_api_session_list_msg_data, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
l2tp_session_incall_ind_1(struct l2tp_api_session_incall_msg_data params, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, L2TP_SESSION_INCALL_IND,
		(xdrproc_t) xdr_l2tp_api_session_incall_msg_data, (caddr_t) &params,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
l2tp_session_profile_create_1(struct l2tp_api_session_profile_msg_data params, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, L2TP_SESSION_PROFILE_CREATE,
		(xdrproc_t) xdr_l2tp_api_session_profile_msg_data, (caddr_t) &params,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
l2tp_session_profile_delete_1(char *name, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, L2TP_SESSION_PROFILE_DELETE,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &name,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
l2tp_session_profile_modify_1(struct l2tp_api_session_profile_msg_data params, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, L2TP_SESSION_PROFILE_MODIFY,
		(xdrproc_t) xdr_l2tp_api_session_profile_msg_data, (caddr_t) &params,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
l2tp_session_profile_get_1(char *name, struct l2tp_api_session_profile_msg_data *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, L2TP_SESSION_PROFILE_GET,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &name,
		(xdrproc_t) xdr_l2tp_api_session_profile_msg_data, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
l2tp_session_profile_list_1(struct l2tp_api_session_profile_list_msg_data *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, L2TP_SESSION_PROFILE_LIST, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_l2tp_api_session_profile_list_msg_data, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
l2tp_ppp_profile_create_1(struct l2tp_api_ppp_profile_msg_data params, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, L2TP_PPP_PROFILE_CREATE,
		(xdrproc_t) xdr_l2tp_api_ppp_profile_msg_data, (caddr_t) &params,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
l2tp_ppp_profile_delete_1(char *name, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, L2TP_PPP_PROFILE_DELETE,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &name,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
l2tp_ppp_profile_modify_1(struct l2tp_api_ppp_profile_msg_data params, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, L2TP_PPP_PROFILE_MODIFY,
		(xdrproc_t) xdr_l2tp_api_ppp_profile_msg_data, (caddr_t) &params,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
l2tp_ppp_profile_get_1(char *name, struct l2tp_api_ppp_profile_msg_data *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, L2TP_PPP_PROFILE_GET,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &name,
		(xdrproc_t) xdr_l2tp_api_ppp_profile_msg_data, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
l2tp_ppp_profile_list_1(struct l2tp_api_ppp_profile_list_msg_data *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, L2TP_PPP_PROFILE_LIST, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_l2tp_api_ppp_profile_list_msg_data, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
l2tp_peer_get_1(struct l2tp_api_ip_addr local_addr, struct l2tp_api_ip_addr peer_addr, struct l2tp_api_peer_msg_data *clnt_res,  CLIENT *clnt)
{
	l2tp_peer_get_1_argument arg;
	arg.local_addr = local_addr;
	arg.peer_addr = peer_addr;
	return (clnt_call (clnt, L2TP_PEER_GET, (xdrproc_t) xdr_l2tp_peer_get_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_l2tp_api_peer_msg_data, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
l2tp_peer_list_1(struct l2tp_api_peer_list_msg_data *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, L2TP_PEER_LIST, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_l2tp_api_peer_list_msg_data, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
l2tp_user_list_1(struct l2tp_api_user_list_msg_data *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, L2TP_USER_LIST, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_l2tp_api_user_list_msg_data, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
l2tp_peer_profile_unset_1(struct l2tp_api_peer_profile_unset_msg_data params, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, L2TP_PEER_PROFILE_UNSET,
		(xdrproc_t) xdr_l2tp_api_peer_profile_unset_msg_data, (caddr_t) &params,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
l2tp_tunnel_profile_unset_1(struct l2tp_api_tunnel_profile_unset_msg_data params, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, L2TP_TUNNEL_PROFILE_UNSET,
		(xdrproc_t) xdr_l2tp_api_tunnel_profile_unset_msg_data, (caddr_t) &params,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
l2tp_session_profile_unset_1(struct l2tp_api_session_profile_unset_msg_data params, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, L2TP_SESSION_PROFILE_UNSET,
		(xdrproc_t) xdr_l2tp_api_session_profile_unset_msg_data, (caddr_t) &params,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
l2tp_ppp_profile_unset_1(struct l2tp_api_ppp_profile_unset_msg_data params, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, L2TP_PPP_PROFILE_UNSET,
		(xdrproc_t) xdr_l2tp_api_ppp_profile_unset_msg_data, (caddr_t) &params,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
l2tp_test_log_1(char *text, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, L2TP_TEST_LOG,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &text,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
l2tp_test_modify_1(struct l2tp_api_test_msg_data params, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, L2TP_TEST_MODIFY,
		(xdrproc_t) xdr_l2tp_api_test_msg_data, (caddr_t) &params,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
l2tp_test_get_1(struct l2tp_api_test_msg_data *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, L2TP_TEST_GET, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_l2tp_api_test_msg_data, (caddr_t) clnt_res,
		TIMEOUT));

}
